resources:
  - type: storage.v1.bucket
    name: sls-handle-github-events-dev-1580210336126
  - type: cloudfunctions.v1beta2.function
    name: handle-github-events-dev-github_event
    properties:
      location: us-central1
      availableMemoryMb: 256
      runtime: python37
      timeout: 60s
      function: github_event
      sourceArchiveUrl: >-
        gs://sls-handle-github-events-dev-1580210336126/serverless/handle-github-events/dev/1580229356955-2020-01-28T16:35:56.955Z/handle-github-events.zip
      environmentVariables:
        GITHUB_WEBHOOK_SECRET: qSLQjtoctYS8
        GCP_KEY_FILE: 'C:\Users\andre\conf\netdata-analytics-ml-ee5f28b8cd5d.json'
        GCP_PROJECT_NAME: netdata-analytics-ml
        GCP_REGION_NAME: us-central1
        BQ_DATASET_NAME: github
        BQ_TABLE_NAME: events
        BQ_IF_EXISTS: append
      labels: {}
      httpsTrigger:
        url: path
